const BadRequestError = require("../../../common/errors/bad-request-error")
const  FORM_MESSAGES = require("../../../config/formValidationMessages")

function validationSignup(PASSWORD, EMAIL,USERNAME){

    if(!PASSWORD) throw new BadRequestError(FORM_MESSAGES.SIGNUP.PASSWORD_IS_REQUIRED)
    if(!EMAIL) throw new BadRequestError(FORM_MESSAGES.SIGNUP.EMAIL_IS_REQUIRED)
    if(!USERNAME) throw new BadRequestError(FORM_MESSAGES.SIGNUP.USERNAME_IS_REQUIRED)
    // if(!res.Token) throw new BadRequestError(FORM_MESSAGES.SIGNUP.PROVIDE_SUFFIECIENT_DETAILS)

    if(!FORM_MESSAGES.SIGNUP.VALIDATION.REGEX.EMAIL_VALIDATION_REGEX.test(EMAIL.toString())) {
      if(!EMAIL.includes("@")) throw new BadRequestError(FORM_MESSAGES.SIGNUP.VALIDATION.EMAIL_VALIDATION.REQUIRED_SYMBOL)
      if(!EMAIL.includes("mail"))  throw new BadRequestError(FORM_MESSAGES.SIGNUP.VALIDATION.EMAIL_VALIDATION.ENTER_VALID_ADDRESS)
      if(!EMAIL.includes(".com")) throw new BadRequestError(FORM_MESSAGES.SIGNUP.VALIDATION.EMAIL_VALIDATION.COM_ERROR)
      else throw new BadRequestError( FORM_MESSAGES.SIGNUP.VALIDATION.EMAIL_VALIDATION.ENTER_VALID_ADDRESS)
    }

    if(!FORM_MESSAGES.SIGNUP.VALIDATION.REGEX.PASSWORD_VALIDATION_REGEX.test(PASSWORD.toString())) {
      if(PASSWORD.length < 8) throw new BadRequestError( FORM_MESSAGES.SIGNUP.VALIDATION.PASSWORD_VALIDATION.MIN_LETTER_VALIDATION)
      if(PASSWORD.length > 12) throw new BadRequestError( FORM_MESSAGES.SIGNUP.VALIDATION.PASSWORD_VALIDATION.MAX_LETTER_VALIDATION)      
    }

    if(!FORM_MESSAGES.SIGNUP.VALIDATION.REGEX.USERNAME_VALIDATION_REGEX.test(USERNAME.toString())) throw new BadRequestError(FORM_MESSAGES.SIGNUP.VALIDATION.USERNAME_VALIDATION.USERNAME_REGEX_VALIDATION)

    return true
}

module.exports = validationSignup